### ISSUE TITLE
Hacer click en cualquier lugar durante el gameplay ocasiona un crasheo

### ISSUE THREAD

**Issue by MisterChief53** [MisterChief53/Coloniam-Deductam#15]
Despues de saltar la pantalla de bienvenida, el juego todavia esta esperando aver si hay un click, y en cuanto lo detecta, hay un crash. Hay que recordar que el mouse durante el gameplay se va a usar para soltar bombas, asi que esto es importante que se arregle.

**Comment by DarthMordred** [comment]
lo arreglamos de una manera, te informamos despues

**Comment by DarthMordred** [comment]
Ahora si jala al 100
