### ISSUE TITLE
Implementar bombas

### ISSUE THREAD

**Issue by MisterChief53** [MisterChief53/Coloniam-Deductam#16]
Bombas con un pequeno delay que destruyan proyectiles y le den chance al jugador para poder tener un respiro o escapar de una mala situacion. Para esto, se tiene que:

- [x] Arreglar #15 
- [x] Hacer Sprite
- [x] Hacer Animacion
- [x] Implementar

**Comment by DarthMordred** [comment]
lo hicimos

**Comment by DarthMordred** [comment]
quedo bien chido ya
te lo enseñamos mañana
