### ISSUE TITLE
Implementar nuevo Algoritmo de deteccion de colisiones

### ISSUE THREAD

**Issue by MisterChief53** [MisterChief53/Coloniam-Deductam#7]
Debemos de dejar de usar lo que estamos usando, ya que detecta la imagen en si para hacer las decisiones, y en sprite circulares termina detectando una hitbox cuadrada. Hay que ver que hacer, minimo el jugador tiene que tener una hitbox precisa.

**Comment by DarthMordred** [comment]
ya jalo mañana te lo enseñamos
